os:
  - linux
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get -y install sendmail mailutils
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
  - 9
  - 10
  - node
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "npm run build"
install:
  - npm install
script:
  - npm run test
